"""drop cuisine_type column

Revision ID: 1c6f3331666d
Revises: 2d57b234fbc9
Create Date: 2025-09-04 16:20:59.548978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6f3331666d'
down_revision = '2d57b234fbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurants_cuisine_type'))
        batch_op.drop_column('cuisine_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_restaurants_cuisine_type'), ['cuisine_type'], unique=False)

    # ### end Alembic commands ###
