"""Remove unused last_login column from users table

Revision ID: 3b9ed67b71d3
Revises: 233be4ea016f
Create Date: 2025-09-05 04:17:33.736366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9ed67b71d3'
down_revision = '233be4ea016f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
