"""Add vegan and guilt_free columns to menu_items

Revision ID: 408050e77188
Revises: 1c6f3331666d
Create Date: 2025-09-05 01:55:25.143500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408050e77188'
down_revision = '1c6f3331666d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vegan', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_guilt_free', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('is_guilt_free')
        batch_op.drop_column('is_vegan')

    # ### end Alembic commands ###
