"""Add last_order_date column for daily order tracking

Revision ID: 5db9c9549efe
Revises: 408050e77188
Create Date: 2025-09-05 03:24:07.698751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db9c9549efe'
down_revision = '408050e77188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_order_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('last_order_date')

    # ### end Alembic commands ###
